# Generated by Django 6.1 on 2026-08-24 23:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('billing', 'Faturamento'), ('shipping', 'Entrega')], max_length=10, verbose_name='tipo')),
                ('first_name', models.CharField(max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(max_length=80, verbose_name='sobrenome')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='NIF / VAT')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='telefone')),
                ('street', models.CharField(max_length=160, verbose_name='endereço')),
                ('street_extra', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('postal_code', models.CharField(max_length=16, verbose_name='código postal')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='região')),
                ('country_code', models.CharField(max_length=2, verbose_name='país (ISO)')),
                ('country_name', models.CharField(max_length=80, verbose_name='país')),
            ],
            options={
                'verbose_name': 'endereço do pedido',
                'verbose_name_plural': 'endereços do pedido',
                'ordering': ('order', 'kind'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='produto (snapshot)')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU (snapshot)')),
                ('variant_label', models.CharField(blank=True, max_length=160, verbose_name='opção (snapshot)')),
                ('color_name', models.CharField(blank=True, max_length=60, verbose_name='cor')),
                ('size_name', models.CharField(blank=True, max_length=60, verbose_name='tamanho')),
                ('material_name', models.CharField(blank=True, max_length=80, verbose_name='material')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço unitário')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total da linha')),
                ('unit_weight_grams', models.PositiveIntegerField(default=0, verbose_name='peso unitário (g)')),
                ('fulfillment_type', models.CharField(choices=[('stock', 'Do estoque'), ('made_to_order', 'Produzido sob encomenda'), ('personalized', 'Personalizado')], default='stock', max_length=20, verbose_name='tipo de atendimento')),
                ('production_days', models.PositiveIntegerField(default=0, help_text='Snapshot: o prazo que valia quando o pedido foi feito.', verbose_name='prazo de produção (dias úteis)')),
                ('personalization_type', models.CharField(blank=True, max_length=20, verbose_name='tipo de personalização')),
                ('personalization_text', models.TextField(blank=True, verbose_name='texto')),
                ('personalization_notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('body', models.TextField(verbose_name='nota')),
            ],
            options={
                'verbose_name': 'nota interna',
                'verbose_name_plural': 'notas internas',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='ano')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='último número')),
            ],
            options={
                'verbose_name': 'sequência de numeração',
                'verbose_name_plural': 'sequências de numeração',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Pedido criado'), ('payment_started', 'Pagamento iniciado'), ('paid', 'Pagamento confirmado'), ('payment_failed', 'Pagamento recusado'), ('confirmed', 'Pedido confirmado'), ('in_production', 'Em produção'), ('ready', 'Pronto para envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('completed', 'Concluído'), ('cancellation_requested', 'Cancelamento solicitado'), ('cancellation_approved', 'Cancelamento aprovado'), ('cancellation_refused', 'Cancelamento recusado'), ('cancelled', 'Pedido cancelado'), ('refunded', 'Reembolsado'), ('stock_shortage', 'Estoque insuficiente'), ('note', 'Observação')], max_length=32, verbose_name='evento')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='quando')),
                ('is_customer_visible', models.BooleanField(default=True, verbose_name='visível para o cliente')),
            ],
            options={
                'verbose_name': 'evento do pedido',
                'verbose_name_plural': 'histórico do pedido',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('provider', models.CharField(default='stripe', max_length=20, verbose_name='provedor')),
                ('provider_session_id', models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session (cs_...).', max_length=255, verbose_name='sessão do provedor')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent (pi_...).', max_length=255, verbose_name='pagamento do provedor')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='moeda')),
                ('status', models.CharField(choices=[('created', 'Criado'), ('processing', 'Processando'), ('succeeded', 'Confirmado'), ('failed', 'Recusado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='created', max_length=20, verbose_name='situação')),
                ('method_label', models.CharField(blank=True, help_text='Ex.: Cartão · Visa ····4242.', max_length=60, verbose_name='meio de pagamento')),
                ('failure_message', models.CharField(blank=True, max_length=300, verbose_name='motivo da recusa')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=20, verbose_name='provedor')),
                ('event_id', models.CharField(max_length=255, verbose_name='id do evento')),
                ('event_type', models.CharField(blank=True, max_length=80, verbose_name='tipo')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
            ],
            options={
                'verbose_name': 'evento do provedor',
                'verbose_name_plural': 'eventos do provedor',
                'ordering': ('-received_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(editable=False, help_text='JD-2026-000001', max_length=24, unique=True, verbose_name='número')),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=20, verbose_name='situação')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Recusado'), ('partially_refunded', 'Parcialmente reembolsado'), ('refunded', 'Reembolsado')], db_index=True, default='pending', max_length=20, verbose_name='pagamento')),
                ('fulfillment_status', models.CharField(choices=[('not_started', 'Não iniciado'), ('in_production', 'Em produção'), ('ready', 'Pronto'), ('shipped', 'Enviado'), ('delivered', 'Entregue')], db_index=True, default='not_started', max_length=20, verbose_name='produção')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='moeda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='frete')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='TVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total')),
                ('tax_country', models.CharField(blank=True, help_text='ISO do país de entrega.', max_length=2, verbose_name='país do imposto')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='alíquota (%)')),
                ('prices_include_tax', models.BooleanField(default=True, help_text='No varejo B2C da UE o preço anunciado inclui a TVA.', verbose_name='preços com TVA incluída')),
                ('shipping_method_label', models.CharField(blank=True, help_text='Nome da transportadora e do método no dia da compra.', max_length=160, verbose_name='método (snapshot)')),
                ('shipping_min_days', models.PositiveIntegerField(default=0, verbose_name='prazo mínimo (dias úteis)')),
                ('shipping_max_days', models.PositiveIntegerField(default=0, verbose_name='prazo máximo (dias úteis)')),
                ('production_days', models.PositiveIntegerField(default=0, verbose_name='prazo de produção (dias úteis)')),
                ('total_weight_grams', models.PositiveIntegerField(default=0, verbose_name='peso total (g)')),
                ('tracking_number', models.CharField(blank=True, max_length=80, verbose_name='código de rastreio')),
                ('is_gift', models.BooleanField(default=False, help_text='A entrega vai para outra pessoa; a fatura continua com o cliente.', verbose_name='enviar como presente')),
                ('gift_message', models.TextField(blank=True, help_text='Reservado: ainda não é pedido no checkout.', verbose_name='mensagem do presente')),
                ('cancellation_status', models.CharField(choices=[('none', 'Sem solicitação'), ('requested', 'Cancelamento solicitado'), ('approved', 'Cancelamento aprovado'), ('refused', 'Cancelamento recusado')], default='none', max_length=20, verbose_name='cancelamento')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='motivo do cliente')),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='solicitado em')),
                ('cancellation_decision_note', models.TextField(blank=True, verbose_name='resposta da loja')),
                ('cancellation_decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('language', models.CharField(blank=True, help_text='Idioma em que o pedido foi feito. Os e-mails saem nele.', max_length=10, verbose_name='idioma do cliente')),
                ('customer_note', models.TextField(blank=True, verbose_name='observação do cliente')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='e-mail de confirmação enviado em')),
                ('shipped_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='e-mail de envio enviado em')),
                ('stock_applied_at', models.DateTimeField(blank=True, help_text='Preenchido uma única vez, na confirmação do pagamento.', null=True, verbose_name='estoque baixado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
