# Generated by Django 6.1 on 2026-08-24 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_address'),
        ('cart', '0002_cart_cartitem'),
        ('catalog', '0002_product_personalization_text_limit_and_more'),
        ('orders', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingmethod', verbose_name='método de entrega'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Apenas referência. O pedido usa os dados copiados abaixo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_addresses', to='accounts.customeraddress', verbose_name='endereço de origem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='cart.customizationupload', verbose_name='arquivo enviado'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='produto'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='opção'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Vazio quando foi o sistema (webhook, rotina).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='por'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='orders.order', verbose_name='pedido'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='order_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderaddress',
            constraint=models.UniqueConstraint(fields=('order', 'kind'), name='order_address_unique_kind'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='webhook_event_unique_per_provider'),
        ),
    ]
