# Generated by Django 6.1 on 2026-08-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ordem de produção enviada em'),
        ),
    ]
