# Generated by Django 6.1 on 2026-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_admin_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='event',
            field=models.CharField(choices=[('created', 'Pedido criado'), ('payment_started', 'Pagamento iniciado'), ('paid', 'Pagamento confirmado'), ('payment_failed', 'Pagamento recusado'), ('confirmed', 'Pedido confirmado'), ('in_production', 'Em produção'), ('ready', 'Pronto para envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('completed', 'Concluído'), ('cancellation_requested', 'Cancelamento solicitado'), ('cancellation_approved', 'Cancelamento aprovado'), ('cancellation_refused', 'Cancelamento recusado'), ('cancelled', 'Pedido cancelado'), ('refunded', 'Reembolsado'), ('stock_shortage', 'Estoque insuficiente'), ('email_resent', 'E-mail reenviado'), ('status_changed', 'Situação alterada'), ('note', 'Observação')], max_length=32, verbose_name='evento'),
        ),
    ]
