# Generated by Django 6.1 on 2026-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_event_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('beneficiary', models.CharField(blank=True, max_length=140, verbose_name='titular da conta')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=15, verbose_name='BIC/SWIFT')),
                ('instructions', models.TextField(blank=True, help_text='Texto que a equipe copia no e-mail. Ex.: use o número do pedido na comunicação.', verbose_name='instruções de pagamento')),
            ],
            options={
                'verbose_name': 'dados para transferência',
                'verbose_name_plural': 'PAGAMENTO — dados para transferência',
            },
        ),
    ]
