# Generated by Django 6.1 on 2026-09-01 18:51

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_banktransfersettings_bankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('sort_order', 'label', 'pk'), 'verbose_name': 'conta bancária', 'verbose_name_plural': 'PAGAMENTO — contas bancárias'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para tirar da lista sem apagar o histórico.', verbose_name='ativa'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='label',
            field=models.CharField(blank=True, help_text='Como a conta aparece na hora de escolher. Ex.: Principal, Belfius PME.', max_length=80, verbose_name='nome da conta'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordem'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_details_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dados bancários enviados em'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='instructions',
            field=models.TextField(blank=True, help_text='Vai no e-mail do cliente. Ex.: use o número do pedido na comunicação.', verbose_name='instruções de pagamento'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='event',
            field=models.CharField(choices=[('created', 'Pedido criado'), ('payment_started', 'Pagamento iniciado'), ('paid', 'Pagamento confirmado'), ('payment_failed', 'Pagamento recusado'), ('confirmed', 'Pedido confirmado'), ('in_production', 'Em produção'), ('ready', 'Pronto para envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('completed', 'Concluído'), ('cancellation_requested', 'Cancelamento solicitado'), ('cancellation_approved', 'Cancelamento aprovado'), ('cancellation_refused', 'Cancelamento recusado'), ('cancelled', 'Pedido cancelado'), ('refunded', 'Reembolsado'), ('stock_shortage', 'Estoque insuficiente'), ('email_resent', 'E-mail reenviado'), ('transfer_details_sent', 'Dados bancários enviados'), ('payment_proof_received', 'Comprovante recebido'), ('status_changed', 'Situação alterada'), ('note', 'Observação')], max_length=32, verbose_name='evento'),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(upload_to=apps.orders.models.payment_proof_upload_to, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='nome original')),
                ('content_type', models.CharField(blank=True, max_length=60, verbose_name='tipo detectado')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='extensão')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'comprovante de pagamento',
                'verbose_name_plural': 'comprovantes de pagamento',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
