# Generated by Django 6.1 on 2026-09-01 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_bankaccount_options_bankaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='A conta que os pedidos por transferência usam automaticamente. Só uma pode ser padrão — marcar outra desmarca esta.', verbose_name='conta padrão'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.bankaccount', verbose_name='conta bancária'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_beneficiary',
            field=models.CharField(blank=True, max_length=140, verbose_name='titular da conta'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=15, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=40, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_instructions',
            field=models.TextField(blank=True, verbose_name='instruções de pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, db_index=True, help_text='Escolhida pelo cliente no checkout. Ex.: transfer, card.', max_length=20, verbose_name='forma de pagamento'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='bank_account_single_default'),
        ),
    ]
