# Generated by Django 6.1 on 2026-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favorite'),
        ('orders', '0008_bankaccount_is_default_order_bank_account_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='chave da finalização'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('checkout_token', ''), _negated=True), fields=('checkout_token',), name='order_unique_checkout_token'),
        ),
        migrations.AddConstraint(
            model_name='paymentproof',
            constraint=models.UniqueConstraint(fields=('order',), name='payment_proof_one_per_order'),
        ),
    ]
