# Generated by Django 6.1 on 2026-09-02 20:27

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_checkout_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('refund_days_min', models.PositiveIntegerField(blank=True, help_text='Deixe em branco enquanto a loja não tiver um prazo definido: sem ele, a mensagem não promete prazo nenhum.', null=True, verbose_name='prazo mínimo de reembolso (dias)')),
                ('refund_days_max', models.PositiveIntegerField(blank=True, help_text='Preencha os dois para a mensagem falar em faixa (ex.: 5 a 10 dias).', null=True, verbose_name='prazo máximo de reembolso (dias)')),
            ],
            options={
                'verbose_name': 'política de cancelamento',
                'verbose_name_plural': 'CANCELAMENTO — texto enviado ao cliente',
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CancellationSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('extra_note', models.TextField(blank=True, help_text='Acrescentada ao fim da mensagem, neste idioma. Deixe em branco para o cliente receber só o texto padrão.', verbose_name='observação extra')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='orders.cancellationsettings', verbose_name='política')),
            ],
            options={
                'verbose_name': 'tradução da política',
                'verbose_name_plural': 'traduções da política',
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='cancellation_settings_unique_language')],
            },
        ),
    ]
