# Generated by Django 6.1 on 2026-09-02 23:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cancellationsettings_cancellationsettingstranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationsettings',
            name='withdrawal_days',
            field=models.PositiveIntegerField(default=14, help_text='Contados a partir da <b>entrega</b>. Catorze dias é o mínimo legal na Bélgica (diretiva 2011/83/UE). A loja pode oferecer mais; menos, não.', verbose_name='prazo de arrependimento (dias corridos)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_auto',
            field=models.BooleanField(default=False, help_text='Aprovado sem análise humana, porque a regra do momento permitia.', verbose_name='decidido pela regra'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decidido por'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='É desta data que corre o prazo legal de arrependimento.', null=True, verbose_name='entregue em'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Identificador da transferência de volta, ou do provedor.', max_length=140, verbose_name='referência do reembolso'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'Sem reembolso'), ('pending', 'Reembolso pendente'), ('partially_refunded', 'Parcialmente reembolsado'), ('refunded', 'Reembolsado')], default='none', max_length=20, verbose_name='reembolso'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor reembolsado'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='Quando o reembolso foi concluído (não quando foi aberto).', null=True, verbose_name='reembolsado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reembolsado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_return_decision',
            field=models.CharField(blank=True, choices=[('', 'Sem decisão'), ('returned', 'Devolvido ao estoque'), ('kept', 'Não devolvido (peça perdida)'), ('on_refund', 'Devolver quando o reembolso for confirmado')], default='', max_length=20, verbose_name='decisão sobre o estoque'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_returned_at',
            field=models.DateTimeField(blank=True, help_text='Marca de idempotência: com ela preenchida, o saldo não volta duas vezes.', null=True, verbose_name='estoque devolvido em'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_taken',
            field=models.PositiveIntegerField(default=0, help_text='Quantas unidades a confirmação do pagamento realmente tirou do estoque. Pode ser menor que a quantidade — houve falta — ou zero (sob encomenda, ou variante que aceita encomenda sem saldo).', verbose_name='unidades tiradas do saldo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_decision_note',
            field=models.TextField(blank=True, help_text='Vai no e-mail de recusa, com estas palavras. Não é nota interna: para isso existem as notas do pedido.', verbose_name='resposta ao cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_started', 'Não iniciado'), ('in_production', 'Em produção'), ('ready', 'Pronto'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('halted', 'Interrompido')], db_index=True, default='not_started', max_length=20, verbose_name='produção'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Recusado'), ('not_charged', 'Não cobrado')], db_index=True, default='pending', max_length=20, verbose_name='pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando pagamento'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='event',
            field=models.CharField(choices=[('created', 'Pedido criado'), ('payment_started', 'Pagamento iniciado'), ('paid', 'Pagamento confirmado'), ('payment_failed', 'Pagamento recusado'), ('confirmed', 'Pedido confirmado'), ('in_production', 'Em produção'), ('ready', 'Pronto para envio'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('completed', 'Concluído'), ('cancellation_requested', 'Cancelamento solicitado'), ('cancellation_approved', 'Cancelamento aprovado'), ('cancellation_refused', 'Cancelamento recusado'), ('cancelled', 'Pedido cancelado'), ('refunded', 'Reembolsado'), ('stock_shortage', 'Estoque insuficiente'), ('stock_returned', 'Estoque devolvido'), ('stock_kept', 'Estoque não devolvido'), ('production_halted', 'Produção interrompida'), ('refund_pending', 'Reembolso pendente'), ('refund_partial', 'Reembolso parcial'), ('email_resent', 'E-mail reenviado'), ('transfer_details_sent', 'Dados bancários enviados'), ('payment_proof_received', 'Comprovante recebido'), ('status_changed', 'Situação alterada'), ('note', 'Observação')], max_length=32, verbose_name='evento'),
        ),
    ]
