# Generated by Django 6.1 on 2026-09-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_sanear_estados_antigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colors_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='cores (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='materials_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='composição de materiais (snapshot)'),
        ),
    ]
