# Generated by Django 6.1 on 2026-09-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_colors_materials_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='opções adicionais (snapshot)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_label',
            field=models.CharField(blank=True, max_length=500, verbose_name='opção (snapshot)'),
        ),
    ]
