# Generated by Django 6.1 on 2026-09-09 23:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_options_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='choices_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='escolhas do cliente (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='adicional das escolhas (unitário)'),
        ),
    ]
