# Generated by Django 6.1 on 2026-08-24 18:31

import apps.accounts.managers
import apps.accounts.models
import apps.accounts.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'Este nome de usuário não está disponível.'}, help_text='Letras, números, hífen e sublinhado. Não pode ser um e-mail.', max_length=30, unique=True, validators=[apps.accounts.validators.UsernameValidator()], verbose_name='nome de usuário')),
                ('email', models.EmailField(error_messages={'unique': 'Já existe uma conta com este e-mail.'}, max_length=254, unique=True, verbose_name='e-mail')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado, o usuário não consegue entrar. Preferir isto a apagar a conta.', verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite entrar no painel administrativo.', verbose_name='acessa o admin')),
                ('email_verified', models.BooleanField(default=False, help_text='Fica marcado quando o cliente clica no link enviado por e-mail.', verbose_name='e-mail confirmado')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmado em')),
                ('verification_sent_at', models.DateTimeField(blank=True, help_text='Usado para limitar reenvios.', null=True, verbose_name='último envio de confirmação')),
                ('preferred_language', models.CharField(default=apps.accounts.models.default_language, help_text='Idioma dos e-mails enviados para este cliente.', max_length=10, verbose_name='idioma preferido')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cadastrado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='sobrenome')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[apps.accounts.validators.validate_phone], verbose_name='telefone')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('vat_number', models.CharField(blank=True, help_text='Número de IVA da empresa (ex.: BE0123456789).', max_length=20, verbose_name='NIF / VAT')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='conta de acesso')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='accounts_user_username_ci_unique', violation_error_message='Já existe um usuário com este nome (maiúsculas não contam).'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique', violation_error_message='Já existe uma conta com este e-mail (maiúsculas não contam).'),
        ),
    ]
