# Generated by Django 6.1 on 2026-08-24 23:09

import apps.accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0004_seed_delivery_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(blank=True, help_text='Como o cliente reconhece este endereço: "Casa", "Trabalho"...', max_length=40, verbose_name='identificação')),
                ('first_name', models.CharField(max_length=80, verbose_name='nome')),
                ('last_name', models.CharField(max_length=80, verbose_name='sobrenome')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('vat_number', models.CharField(blank=True, help_text='Só quando a fatura sai em nome de uma empresa.', max_length=20, verbose_name='NIF / VAT')),
                ('phone', models.CharField(blank=True, help_text='A transportadora usa em caso de problema na entrega.', max_length=25, validators=[apps.accounts.validators.validate_phone], verbose_name='telefone')),
                ('street', models.CharField(max_length=160, verbose_name='endereço')),
                ('street_extra', models.CharField(blank=True, help_text='Andar, caixa postal, ponto de referência.', max_length=120, verbose_name='complemento')),
                ('postal_code', models.CharField(max_length=16, verbose_name='código postal')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='região / província')),
                ('is_default_shipping', models.BooleanField(default=False, verbose_name='padrão para entrega')),
                ('is_default_billing', models.BooleanField(default=False, verbose_name='padrão para faturamento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.deliverycountry', verbose_name='país')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ('-is_default_shipping', '-is_default_billing', 'label', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('customer',), name='one_default_shipping_per_customer'), models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('customer',), name='one_default_billing_per_customer')],
            },
        ),
    ]
