# Generated by Django 6.1 on 2026-08-24 14:23

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.SlugField(blank=True, help_text='Identificador para URL. Gerado a partir do nome quando deixado em branco.', max_length=220, unique=True, verbose_name='slug')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primeiro dentro do mesmo nível.', verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('parent', models.ForeignKey(blank=True, help_text='Deixe vazio para uma categoria de primeiro nível.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category', verbose_name='categoria pai')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('sort_order', 'slug'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'tradução da categoria',
                'verbose_name_plural': 'traduções da categoria',
                'ordering': ('language',),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='category_parent_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='category_parent_is_not_self'),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='category_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='category_translation_name_not_empty'),
        ),
    ]
