# Generated by Django 6.1 on 2026-08-24 17:01

import apps.cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('file', models.FileField(upload_to=apps.cart.models.customization_upload_to, verbose_name='arquivo')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='nome original')),
                ('content_type', models.CharField(blank=True, max_length=60, verbose_name='tipo detectado')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='extensão')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='De quem enviou. Serve para limpeza de arquivos órfãos.', max_length=64, verbose_name='sessão')),
            ],
            options={
                'verbose_name': 'arquivo de personalização',
                'verbose_name_plural': 'arquivos de personalização',
                'ordering': ('-created_at',),
            },
        ),
    ]
