# Generated by Django 6.1 on 2026-09-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='choices',
            field=models.JSONField(blank=True, default=dict, verbose_name='escolhas do cliente'),
        ),
    ]
