# Generated by Django 6.1 on 2026-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='idioma')),
                ('is_active', models.BooleanField(default=False, help_text='Desmarcado, o idioma some do seletor e a loja recusa a troca para ele.', verbose_name='disponível na loja')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordem no seletor do header.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'idioma da loja',
                'verbose_name_plural': 'idiomas da loja',
                'ordering': ('sort_order', 'code'),
            },
        ),
    ]
