# Generated by Django 6.1 on 2026-08-24 23:07

import apps.core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_site_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alfa-2, em maiúsculas: BE, FR, NL, DE...', max_length=2, unique=True, verbose_name='código ISO')),
                ('is_active', models.BooleanField(default=False, help_text='Desmarcado, o país some do checkout e do cadastro de endereços.', verbose_name='envia para este país')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='Alíquota aplicada a pedidos entregues neste país.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TVA (%)')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Ordem na lista do checkout.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'país de entrega',
                'verbose_name_plural': 'países de entrega',
                'ordering': ('sort_order', 'iso_code'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeliveryCountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.deliverycountry', verbose_name='país')),
            ],
            options={
                'verbose_name': 'nome do país',
                'verbose_name_plural': 'nomes do país',
                'ordering': ('master', 'language'),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='delivery_country_unique_language')],
            },
        ),
    ]
