# Generated by Django 6.1 on 2026-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_country_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=False, help_text='Desmarcada, a loja volta a usar as variáveis do .env. Marque só depois de testar o envio.', verbose_name='usar esta configuração')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='servidor SMTP')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='porta')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='usuário')),
                ('password_encrypted', models.TextField(blank=True, editable=False, verbose_name='senha (cifrada)')),
                ('use_tls', models.BooleanField(default=True, help_text='O normal na porta 587. Não marque junto com SSL.', verbose_name='usar TLS (STARTTLS)')),
                ('use_ssl', models.BooleanField(default=False, help_text='O normal na porta 465. Não marque junto com TLS.', verbose_name='usar SSL')),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Quanto esperar pelo servidor antes de desistir de um envio.', verbose_name='tempo limite (s)')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail remetente')),
                ('from_name', models.CharField(blank=True, max_length=120, verbose_name='nome do remetente')),
                ('reply_to', models.EmailField(blank=True, help_text='Para onde vai a resposta do cliente. Vazio: o próprio remetente.', max_length=254, verbose_name='e-mail de resposta')),
                ('admin_recipients', models.TextField(blank=True, help_text='Um por linha, ou separados por vírgula. É para cá que vai a ordem de produção de cada pedido novo.', verbose_name='e-mails que recebem os pedidos')),
                ('last_test_at', models.DateTimeField(blank=True, null=True, verbose_name='último teste em')),
                ('last_test_ok', models.BooleanField(default=False, verbose_name='último teste funcionou')),
                ('last_test_message', models.CharField(blank=True, max_length=300, verbose_name='resultado do último teste')),
            ],
            options={
                'verbose_name': 'configuração de e-mail',
                'verbose_name_plural': 'configuração de e-mail',
            },
        ),
    ]
