# Generated by Django 6.1 on 2026-08-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='contact_recipients',
            field=models.TextField(blank=True, help_text='Um por linha, ou separados por vírgula. Recebem as mensagens do formulário de contato e os pedidos de revenda. Em branco, vão para quem recebe os pedidos.', verbose_name='e-mails que recebem os contatos'),
        ),
    ]
