# Generated by Django 6.1 on 2026-09-03 15:50

import apps.core.models
import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailsettings_contact_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('header_logo', models.FileField(blank=True, help_text='Aparece no cabeçalho, sobre fundo claro. Altura de exibição: 40 px — envie com o dobro para telas retina. SVG é o formato preferido.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='logo do topo')),
                ('footer_logo', models.FileField(blank=True, help_text='Aparece no rodapé, sobre fundo escuro — normalmente é a versão clara da logo. Em branco, o rodapé usa a marca tipográfica.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='logo do rodapé')),
                ('favicon', models.FileField(blank=True, help_text='O ícone da aba do navegador. Quadrado, a partir de 48×48 px. Em branco, a página sai sem ícone — o navegador mostra o dele.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='favicon')),
                ('product_placeholder', models.FileField(blank=True, help_text='Usada só onde o produto ainda não tem foto própria. Quadrada (1:1). Em branco, aparece o espaço reservado com a inicial do produto — nunca uma foto de outro produto.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='imagem padrão dos produtos')),
            ],
            options={
                'verbose_name': 'logos e imagens',
                'verbose_name_plural': 'LOGOS E IMAGENS',
            },
        ),
    ]
