# Generated by Django 6.1 on 2026-09-03 20:25

import apps.core.models
import apps.core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brand_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandassets',
            name='favicon',
            field=models.FileField(blank=True, help_text='<b>Onde aparece:</b> na aba do navegador e nos favoritos (<code>&lt;link rel="icon"&gt;</code>), e no atalho <code>/favicon.ico</code>. Independente das duas logos: num quadrado de 32 px a marca completa não se lê, e o que funciona é o símbolo sozinho.<br><b>Tamanho recomendado:</b> 512 × 512 px (135,47 × 135,47 mm a 96 DPI), quadrado. Recomendação, não exigência — o navegador redimensiona.<br><b>Em branco:</b> a página sai sem ícone e o navegador mostra o dele.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='brandassets',
            name='footer_logo',
            field=models.FileField(blank=True, help_text='<b>Onde aparece:</b> no rodapé, e <b>só</b> nele. É independente da logo do topo: o rodapé tem fundo escuro, e a mesma marca costuma sumir ali — normalmente se envia aqui a versão clara.<br><b>Tamanho recomendado:</b> 500 × 150 px (132,29 × 39,69 mm a 96 DPI). Recomendação, não exigência.<br><b>Em branco:</b> o rodapé mostra a marca tipográfica.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='logo do rodapé'),
        ),
        migrations.AlterField(
            model_name='brandassets',
            name='header_logo',
            field=models.FileField(blank=True, help_text='<b>Onde aparece:</b> no cabeçalho de todas as páginas, sobre fundo claro.<br><b>Tamanho recomendado:</b> 600 × 150 px (158,75 × 39,69 mm a 96 DPI). É uma recomendação, não uma exigência — qualquer imagem é aceita e o cabeçalho a ajusta para 40 px de altura.<br>SVG é o formato preferido: vetor não borra em tela retina, e aí a medida em pixels deixa de importar.<br><b>Em branco:</b> o cabeçalho mostra a marca tipográfica. O site não quebra.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='logo do topo'),
        ),
        migrations.AlterField(
            model_name='brandassets',
            name='product_placeholder',
            field=models.FileField(blank=True, help_text='<b>Onde aparece:</b> <b>apenas</b> nos produtos que ainda não têm foto própria. Nenhum produto com foto é afetado — esta imagem nunca substitui uma existente.<br><b>Tamanho recomendado:</b> 1000 × 1000 px (264,58 × 264,58 mm a 96 DPI), quadrada, porque o card do produto é 1:1. Recomendação, não exigência.<br><b>Em branco:</b> aparece o espaço reservado com a inicial do produto — nunca a foto de outro produto.', upload_to=apps.core.models.brand_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif']), apps.core.uploads.validate_brand_image], verbose_name='imagem padrão dos produtos'),
        ),
    ]
