# Generated by Django 6.1 on 2026-09-10 22:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brand_assets_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycountry',
            name='free_shipping_enabled',
            field=models.BooleanField(default=False, help_text='Ligado, pedidos que alcançarem o valor abaixo não pagam entrega neste país. Os outros países não são afetados.', verbose_name='frete grátis neste país'),
        ),
        migrations.AddField(
            model_name='deliverycountry',
            name='free_shipping_min_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='O valor dos produtos (sem a entrega) a partir do qual o frete para este país sai zero. Ex.: 50,00 — a partir de € 50,00 a entrega é grátis. Vale só com a opção acima ligada.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='frete grátis a partir de (€)'),
        ),
    ]
