# Generated by Django 6.1 on 2026-09-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delivery_country_free_shipping'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycountry',
            name='free_shipping_carrier',
            field=models.ForeignKey(blank=True, help_text='Quem entrega de graça neste país quando o pedido alcança o valor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_shipping_countries', to='shipping.shippingcarrier', verbose_name='transportadora do frete grátis'),
        ),
        migrations.AddField(
            model_name='deliverycountry',
            name='free_shipping_method',
            field=models.ForeignKey(blank=True, help_text='A modalidade **dessa** transportadora que sai zero. As outras continuam com o preço da tabela, e o cliente escolhe no checkout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_shipping_countries', to='shipping.shippingmethod', verbose_name='modalidade grátis'),
        ),
    ]
