# Generated by Django 6.1 on 2026-08-24 14:50

import apps.core.models
import apps.home.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cta_target', models.CharField(choices=[('none', 'Sem botão'), ('category', 'Categoria'), ('product', 'Produto'), ('url', 'Endereço livre')], default='none', max_length=10, verbose_name='destino do botão')),
                ('cta_url', models.CharField(blank=True, help_text='Use apenas quando o destino não for uma categoria ou produto.', max_length=500, verbose_name='endereço do botão')),
                ('internal_name', models.CharField(help_text='Identificação administrativa. Não aparece para o cliente.', max_length=120, verbose_name='nome interno')),
                ('image_desktop', models.FileField(blank=True, help_text='Proporção recomendada: 16:6 (ex.: 1920×720).', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='imagem (desktop)')),
                ('image_mobile', models.FileField(blank=True, help_text='Opcional. Proporção recomendada: 4:5 (ex.: 900×1125).', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='imagem (mobile)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('cta_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category', verbose_name='categoria de destino')),
                ('cta_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='produto de destino')),
            ],
            options={
                'verbose_name': 'banner da Home',
                'verbose_name_plural': 'banners da Home',
                'ordering': ('sort_order', '-created_at'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeBannerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='texto do botão')),
                ('image_alt', models.CharField(blank=True, help_text='Descrição da imagem para leitores de tela.', max_length=200, verbose_name='texto alternativo da imagem')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homebanner', verbose_name='banner')),
            ],
            options={
                'verbose_name': 'tradução do banner',
                'verbose_name_plural': 'traduções do banner',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cta_target', models.CharField(choices=[('none', 'Sem botão'), ('category', 'Categoria'), ('product', 'Produto'), ('url', 'Endereço livre')], default='none', max_length=10, verbose_name='destino do botão')),
                ('cta_url', models.CharField(blank=True, help_text='Use apenas quando o destino não for uma categoria ou produto.', max_length=500, verbose_name='endereço do botão')),
                ('internal_name', models.CharField(help_text="Identificação administrativa (ex.: 'Destaques de Modelos'). Não aparece para o cliente.", max_length=120, verbose_name='nome interno')),
                ('section_type', models.CharField(choices=[('manual', 'Produtos escolhidos manualmente'), ('category', 'Produtos de uma categoria'), ('featured', 'Produtos em destaque'), ('newest', 'Novidades (produtos mais recentes)'), ('best_sellers', 'Mais vendidos (aguarda o módulo de pedidos)')], default='featured', max_length=20, verbose_name='tipo')),
                ('layout', models.CharField(choices=[('grid', 'Grade'), ('carousel', 'Carrossel')], default='grid', max_length=10, verbose_name='layout')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para esconder sem apagar (campanhas sazonais).', verbose_name='ativa')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primeiro na Home.', verbose_name='ordem')),
                ('product_limit', models.PositiveIntegerField(default=4, help_text='Máximo de produtos exibidos (1 a 24).', verbose_name='quantidade de produtos')),
                ('include_subcategories', models.BooleanField(default=True, help_text='Traz também os produtos das categorias filhas.', verbose_name='incluir subcategorias')),
                ('category', models.ForeignKey(blank=True, help_text="Usada apenas no tipo 'Produtos de uma categoria'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_sections', to='categories.category', verbose_name='categoria')),
                ('cta_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category', verbose_name='categoria de destino')),
                ('cta_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='produto de destino')),
            ],
            options={
                'verbose_name': 'seção da Home',
                'verbose_name_plural': 'seções da Home',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_section_items', to='catalog.product', verbose_name='produto')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homesection', verbose_name='seção')),
            ],
            options={
                'verbose_name': 'produto da seção',
                'verbose_name_plural': 'produtos da seção',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='homesection',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='home_sections', through='home.HomeSectionProduct', to='catalog.product', verbose_name='produtos'),
        ),
        migrations.CreateModel(
            name='HomeSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='subtítulo')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='texto do botão')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homesection', verbose_name='seção')),
            ],
            options={
                'verbose_name': 'tradução da seção',
                'verbose_name_plural': 'traduções da seção',
                'ordering': ('language',),
            },
        ),
        migrations.AddIndex(
            model_name='homebanner',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_banner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='homebannertranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='home_banner_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='homebannertranslation',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='home_banner_translation_title_not_empty'),
        ),
        migrations.AddIndex(
            model_name='homesectionproduct',
            index=models.Index(fields=['section', 'sort_order'], name='home_section_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='homesectionproduct',
            constraint=models.UniqueConstraint(fields=('section', 'product'), name='home_section_product_unique'),
        ),
        migrations.AddIndex(
            model_name='homesection',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_section_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='homesection',
            constraint=models.CheckConstraint(condition=models.Q(('product_limit__gte', 1), ('product_limit__lte', 24)), name='home_section_product_limit_range'),
        ),
        migrations.AddConstraint(
            model_name='homesection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('section_type', 'category'), _negated=True), ('category__isnull', False), _connector='OR'), name='home_section_category_required_for_category_type'),
        ),
        migrations.AddConstraint(
            model_name='homesectiontranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='home_section_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='homesectiontranslation',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='home_section_translation_title_not_empty'),
        ),
    ]
