# Generated by Django 6.1 on 2026-08-27 20:07

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_media_variant_link'),
        ('categories', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCallout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cta_target', models.CharField(choices=[('none', 'Sem botão'), ('category', 'Categoria'), ('product', 'Produto'), ('url', 'Endereço livre')], default='none', max_length=10, verbose_name='destino do botão')),
                ('cta_url', models.CharField(blank=True, help_text='Use apenas quando o destino não for uma categoria ou produto.', max_length=500, verbose_name='endereço do botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='exibir na Home')),
            ],
            options={
                'verbose_name': 'chamada final da Home',
                'verbose_name_plural': 'CHAMADA FINAL — faixa do fim da Home',
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeCalloutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='sobretítulo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='texto do botão')),
            ],
            options={
                'verbose_name': 'tradução da chamada',
                'verbose_name_plural': 'traduções da chamada',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(help_text='Identificação administrativa. Não aparece para o cliente.', max_length=120, verbose_name='nome interno')),
                ('icon', models.CharField(choices=[('cube', 'Cubo (produção)'), ('palette', 'Paleta (cores e materiais)'), ('sparkles', 'Brilho (personalização)'), ('truck', 'Caminhão (envio)'), ('shield', 'Escudo (segurança)'), ('clock', 'Relógio (prazo)'), ('package', 'Caixa (embalagem)'), ('heart', 'Coração'), ('check', 'Confirmação'), ('globe', 'Globo')], default='cube', max_length=20, verbose_name='ícone')),
                ('accent', models.CharField(choices=[('brand', 'Roxo'), ('cyan', 'Ciano'), ('magenta', 'Magenta')], default='brand', max_length=10, verbose_name='cor do ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'card da Home',
                'verbose_name_plural': 'CARDS — como trabalhamos',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeCardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'tradução do card',
                'verbose_name_plural': 'traduções do card',
                'ordering': ('language',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='homebannertranslation',
            name='home_banner_translation_title_not_empty',
        ),
        migrations.AlterField(
            model_name='homebannertranslation',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional. Em branco, a imagem aparece sozinha — sem faixa escura nem título vazio por cima dela.', max_length=200, verbose_name='título'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='cta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category', verbose_name='categoria de destino'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='cta_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='produto de destino'),
        ),
        migrations.AddField(
            model_name='homecallouttranslation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homecallout', verbose_name='chamada'),
        ),
        migrations.AddIndex(
            model_name='homecard',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_card_active_idx'),
        ),
        migrations.AddField(
            model_name='homecardtranslation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homecard', verbose_name='card'),
        ),
        migrations.AddConstraint(
            model_name='homecallouttranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='home_callout_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='homecardtranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='home_card_translation_unique_language'),
        ),
    ]
