# Generated by Django 6.1 on 2026-09-01 18:51

import apps.home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homecallout_homecallouttranslation_homecard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image_desktop',
            field=models.FileField(blank=True, help_text='1920 × 700 px — proporção 2,74:1. Fora dessa medida a imagem é cortada pelo centro para caber na faixa.', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='imagem (desktop)'),
        ),
    ]
