# Generated by Django 6.1 on 2026-09-04 09:52

from django.db import migrations, models


def banners_existentes_seguem_como_estao(apps, schema_editor):
    """Quem ja esta no ar nao muda de desenho por causa desta migracao.

    O campo `layout` nasce com `editorial` porque e esse o desenho da marca e
    o que se quer nos cadastros novos. Mas um banner que ja existe foi
    cadastrado como arte de faixa inteira, com a imagem cortada em 2,74:1 --
    passa-lo para editorial mudaria a Home de producao sozinho, no deploy.

    Entao os que ja existem ficam em `full_image`, que e exatamente o que eles
    fazem hoje. Trocar para editorial vira uma decisao do Admin, tomada quando
    houver a foto certa para o quadro.
    """
    HomeBanner = apps.get_model("home", "HomeBanner")
    HomeBanner.objects.update(layout="full_image")


def desfazer(apps, schema_editor):
    """Nada a desfazer: a coluna inteira sai no `RemoveField` seguinte."""



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_card_accent_semantic_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='cta_secondary_url',
            field=models.CharField(blank=True, help_text='Só no hero editorial. Em branco, o segundo botão não aparece.', max_length=500, verbose_name='endereço do segundo botão'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='frame_color',
            field=models.CharField(choices=[('lavender', 'Lavanda'), ('mint', 'Menta'), ('yellow', 'Amarelo'), ('coral', 'Coral')], default='lavender', max_length=10, verbose_name='cor do quadro da foto'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='layout',
            field=models.CharField(choices=[('editorial', 'Hero editorial (texto + composição gráfica)'), ('full_image', 'Imagem completa (a arte ocupa o banner)')], default='editorial', help_text='<b>Hero editorial</b>: o texto fica à esquerda e a foto entra no quadro da composição, com os selos por cima.<br><b>Imagem completa</b>: a arte ocupa o banner inteiro.', max_length=12, verbose_name='tipo de banner'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='plate_color',
            field=models.CharField(choices=[('purple', 'Roxo'), ('navy', 'Navy'), ('mint', 'Menta'), ('coral', 'Coral')], default='purple', max_length=10, verbose_name='cor da placa de trás'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='surface_color',
            field=models.CharField(choices=[('cream', 'Creme'), ('lavender', 'Lavanda'), ('white', 'Branco')], default='cream', max_length=10, verbose_name='fundo do bloco'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='badge_mint',
            field=models.CharField(blank=True, help_text='Ex.: "+120 cores".', max_length=40, verbose_name='selo menta'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='badge_white',
            field=models.CharField(blank=True, help_text='Ex.: "★ 4.9 · 300+ pedidos".', max_length=40, verbose_name='selo branco'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='badge_yellow',
            field=models.CharField(blank=True, help_text='Ex.: "PLA · 0.12 mm".', max_length=40, verbose_name='selo amarelo'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='cta_secondary_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='texto do segundo botão'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='A pílula amarela inclinada. Ex.: "Impressão 3D criativa".', max_length=60, verbose_name='tarja acima do título'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='perk_1',
            field=models.CharField(blank=True, max_length=60, verbose_name='promessa 1'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='perk_2',
            field=models.CharField(blank=True, max_length=60, verbose_name='promessa 2'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='perk_3',
            field=models.CharField(blank=True, max_length=60, verbose_name='promessa 3'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='title_highlight',
            field=models.CharField(blank=True, help_text='Um trecho que já exista no título; ele sai em roxo. Ex.: com o título "Ideias que ganham forma", escreva <b>forma</b> aqui.', max_length=80, verbose_name='palavra destacada no título'),
        ),
            migrations.RunPython(
            banners_existentes_seguem_como_estao, desfazer, elidable=False
        ),
    ]
