# Generated by Django 6.1 on 2026-09-04 11:20

import apps.core.colors
import apps.core.models
import apps.home.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('home', '0005_banner_editorial_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='exibir na Home')),
                ('image', models.FileField(blank=True, help_text='Entra dentro do quadro. Proporção 4:3 (ex.: 1000 × 750 px).', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='imagem')),
                ('frame_color', models.CharField(choices=[('lavender', 'Lavanda'), ('mint', 'Menta'), ('yellow', 'Amarelo'), ('coral', 'Coral')], default='yellow', max_length=10, verbose_name='cor do quadro')),
                ('surface_color', models.CharField(default='cream', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='fundo do bloco')),
                ('text_color', models.CharField(default='ink-soft', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto')),
            ],
            options={
                'verbose_name': 'bloco Sobre a loja',
                'verbose_name_plural': 'SOBRE A LOJA — quadro de imagem e texto',
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='cta_bg_color',
            field=models.CharField(default='yellow', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do botão'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='cta_text_color',
            field=models.CharField(default='navy', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto do botão'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='eyebrow_color',
            field=models.CharField(default='yellow', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do sobretítulo'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='step_bg_color',
            field=models.CharField(default='navy-soft', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='fundo dos blocos dos passos'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='surface_color',
            field=models.CharField(default='navy', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='fundo da faixa'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='text_color',
            field=models.CharField(default='ink-on-deep', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='title_color',
            field=models.CharField(default='white', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do título'),
        ),
        migrations.CreateModel(
            name='HomeAboutBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(max_length=120, verbose_name='nome interno')),
                ('bg_color', models.CharField(default='lavender', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor de fundo')),
                ('text_color', models.CharField(default='purple', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='home.homeabout', verbose_name='bloco')),
            ],
            options={
                'verbose_name': 'pílula',
                'verbose_name_plural': 'PÍLULAS — as etiquetas coloridas',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeCalloutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(max_length=120, verbose_name='nome interno')),
                ('icon', models.CharField(blank=True, choices=[('cube', 'Cubo (produção)'), ('palette', 'Paleta (cores e materiais)'), ('sparkles', 'Brilho (personalização)'), ('truck', 'Caminhão (envio)'), ('shield', 'Escudo (segurança)'), ('clock', 'Relógio (prazo)'), ('package', 'Caixa (embalagem)'), ('heart', 'Coração'), ('check', 'Confirmação'), ('globe', 'Globo')], default='', max_length=20, verbose_name='ícone')),
                ('accent_color', models.CharField(default='mint', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do bloco do número')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('callout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='home.homecallout', verbose_name='chamada')),
            ],
            options={
                'verbose_name': 'passo da chamada',
                'verbose_name_plural': 'PASSOS — os blocos numerados',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeCategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(help_text='Identificação administrativa. Não aparece para o cliente.', max_length=120, verbose_name='nome interno')),
                ('icon', models.CharField(blank=True, choices=[('cube', 'Cubo (produção)'), ('palette', 'Paleta (cores e materiais)'), ('sparkles', 'Brilho (personalização)'), ('truck', 'Caminhão (envio)'), ('shield', 'Escudo (segurança)'), ('clock', 'Relógio (prazo)'), ('package', 'Caixa (embalagem)'), ('heart', 'Coração'), ('check', 'Confirmação'), ('globe', 'Globo')], default='', max_length=20, verbose_name='ícone')),
                ('image', models.FileField(blank=True, help_text='Opcional, no lugar do ícone. Proporção quadrada (ex.: 400 × 400 px).', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='imagem')),
                ('bg_color', models.CharField(default='purple', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor de fundo')),
                ('text_color', models.CharField(default='white', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto')),
                ('accent_color', models.CharField(blank=True, default='', help_text='Em branco, acompanha a cor do texto. Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do ícone e da seta')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('category', models.ForeignKey(blank=True, help_text='Sem categoria, o bloco aparece sem link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='categories.category', verbose_name='categoria de destino')),
            ],
            options={
                'verbose_name': 'card de categoria',
                'verbose_name_plural': 'CATEGORIAS — blocos coloridos da Home',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeCategoryCardTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('eyebrow', models.CharField(blank=True, help_text='O texto pequeno em maiúsculas. Ex.: "48 modelos".', max_length=60, verbose_name='linha de cima')),
                ('title', models.CharField(blank=True, help_text='Em branco, usa o nome da categoria.', max_length=80, verbose_name='título')),
                ('text', models.CharField(blank=True, max_length=160, verbose_name='descrição curta')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homecategorycard', verbose_name='card')),
            ],
            options={
                'verbose_name': 'tradução do card',
                'verbose_name_plural': 'traduções do card',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='HomeAboutBadgeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('text', models.CharField(blank=True, max_length=80, verbose_name='texto')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homeaboutbadge', verbose_name='pílula')),
            ],
            options={
                'verbose_name': 'tradução da pílula',
                'verbose_name_plural': 'traduções da pílula',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='home_badge_translation_unique_language')],
            },
        ),
        migrations.CreateModel(
            name='HomeAboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('eyebrow', models.CharField(blank=True, max_length=80, verbose_name='sobretítulo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('text', models.TextField(blank=True, verbose_name='texto')),
                ('image_alt', models.CharField(blank=True, help_text='Descrição da imagem para leitores de tela.', max_length=200, verbose_name='texto alternativo da imagem')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homeabout', verbose_name='bloco')),
            ],
            options={
                'verbose_name': 'tradução do bloco',
                'verbose_name_plural': 'traduções do bloco',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='home_about_translation_unique_language')],
            },
        ),
        migrations.CreateModel(
            name='HomeCalloutStepTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='título')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.homecalloutstep', verbose_name='passo')),
            ],
            options={
                'verbose_name': 'tradução do passo',
                'verbose_name_plural': 'traduções do passo',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='home_step_translation_unique_language')],
            },
        ),
        migrations.AddIndex(
            model_name='homecategorycard',
            index=models.Index(fields=['is_active', 'sort_order'], name='home_catcard_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='homecategorycardtranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='home_catcard_translation_unique_language'),
        ),
    ]
