# Generated by Django 6.1 on 2026-09-04 19:55

import apps.home.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home_visual_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='image_tile_left',
            field=models.FileField(blank=True, help_text='Quadrada (ex.: 600 × 600 px). Só no Poster Pop.', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='quadro da esquerda (Poster Pop)'),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='image_tile_right',
            field=models.FileField(blank=True, help_text='Quadrada (ex.: 600 × 600 px). Só no Poster Pop.', upload_to=apps.home.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif'])], verbose_name='quadro da direita (Poster Pop)'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='badge_coral',
            field=models.CharField(blank=True, help_text='Bento Criativo: o selo inclinado no canto do cartão branco. Ex.: "Feito na Bélgica".', max_length=40, verbose_name='selo coral'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='colors_note',
            field=models.CharField(blank=True, help_text='Bento Criativo: a linha pequena abaixo do texto grande do cartão roxo. Ex.: "PLA · PETG · TPU". O texto grande é o <b>selo menta</b> ("+120 cores").', max_length=60, verbose_name='nota do cartão de cores'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='image_tile_left_alt',
            field=models.CharField(blank=True, help_text='Poster Pop. Descrição da foto do quadro da esquerda para leitores de tela.', max_length=200, verbose_name='texto alternativo do quadro da esquerda'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='image_tile_right_alt',
            field=models.CharField(blank=True, help_text='Poster Pop. Descrição da foto do quadro da direita para leitores de tela.', max_length=200, verbose_name='texto alternativo do quadro da direita'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='rating_note',
            field=models.CharField(blank=True, help_text='Bento Criativo: a linha pequena do cartão amarelo. Ex.: "300+ pedidos entregues".', max_length=60, verbose_name='nota do cartão de avaliação'),
        ),
        migrations.AddField(
            model_name='homebannertranslation',
            name='rating_value',
            field=models.CharField(blank=True, help_text='Bento Criativo: o número grande do cartão amarelo. Ex.: "4.9". Em branco, o cartão não aparece.', max_length=10, verbose_name='nota da avaliação'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='layout',
            field=models.CharField(choices=[('editorial', 'Hero editorial (texto + composição gráfica)'), ('full_image', 'Imagem completa (a arte ocupa o banner)'), ('poster_pop', 'Poster Pop (poster roxo, conteúdo centrado)'), ('bento_criativo', 'Bento Criativo (grade de cartões)')], default='editorial', help_text='<b>Hero editorial</b>: o texto fica à esquerda e a foto entra no quadro da composição, com os selos por cima.<br><b>Imagem completa</b>: a arte ocupa o banner inteiro.<br><b>Poster Pop</b>: poster roxo com o texto centrado, a palavra destacada em amarelo, os selos menta e branco e três quadros de foto na base.<br><b>Bento Criativo</b>: grade de cartões — o texto no cartão branco, a foto no cartão menta, e embaixo os cartões de cores (roxo) e de avaliação (amarelo).', max_length=20, verbose_name='tipo de banner'),
        ),
    ]
