# Generated by Django 6.1 on 2026-09-04 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_banner_poster_pop_bento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBannerCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('autoplay', models.BooleanField(default=False, help_text='Ligada, os banners trocam sozinhos no intervalo abaixo. Quem pediu ao navegador menos movimento (prefers-reduced-motion) não recebe a rotação, só a navegação manual.', verbose_name='rotação automática')),
                ('interval_seconds', models.PositiveSmallIntegerField(default=5, help_text='Quanto tempo cada banner fica na tela antes de trocar. Entre 2 e 30 segundos.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='intervalo (segundos)')),
                ('show_arrows', models.BooleanField(default=True, help_text='Os botões de anterior e próximo, nas bordas do banner.', verbose_name='mostrar setas')),
                ('show_dots', models.BooleanField(default=True, help_text='As bolinhas abaixo do banner, uma por slide; a do slide atual fica cheia.', verbose_name='mostrar indicadores')),
                ('pause_on_hover', models.BooleanField(default=True, help_text='A rotação automática para enquanto o cursor (ou o foco do teclado) estiver sobre o banner.', verbose_name='pausar ao passar o mouse')),
                ('pause_on_interaction', models.BooleanField(default=True, help_text='Depois de um clique numa seta ou indicador, de uma tecla ou de um deslize no celular, a rotação espera dois intervalos antes de voltar.', verbose_name='pausar após interação')),
            ],
            options={
                'verbose_name': 'carrossel de banners',
                'verbose_name_plural': 'CARROSSEL DE BANNERS — rotação e controles',
            },
        ),
    ]
