# Generated by Django 6.1 on 2026-09-06 21:47

"""A Home vira uma composição: os blocos que tinham posição fixa no template
(categorias em destaque, como trabalhamos, chamada final, sobre a loja) passam
a ser seções de `HomeSection`, na ordem em que sempre apareceram.

A etapa de dados **preserva tudo**: nenhum card, bloco, chamada, passo, pílula
ou tradução é apagado ou recriado. Ela só cria as linhas de seção que
representam a página de hoje e liga o conteúdo existente a elas:

    [categorias em destaque]  <- os HomeCategoryCard existentes
    ...as seções de produtos, na ordem em que estavam...
    [como trabalhamos]        <- os HomeCard existentes (sem nenhum: os padrão)
    [chamada final]           <- o HomeCallout pk=1 (sem linha: o texto padrão)
    [sobre a loja]            <- o HomeAbout pk=1 (só se existir)

e renumera a ordem de dez em dez, para sobrar espaço entre elas. Num banco
sem nenhum conteúdo de Home (uma instalação nova) nada é criado: a Home mostra
a composição padrão até o primeiro cadastro.
"""

import django.db.models.deletion
from django.db import migrations, models

BLOCOS = ("category_cards", "how_we_work", "callout", "about")


def compor(apps, schema_editor):
    HomeSection = apps.get_model("home", "HomeSection")
    HomeCard = apps.get_model("home", "HomeCard")
    HomeCategoryCard = apps.get_model("home", "HomeCategoryCard")
    HomeCallout = apps.get_model("home", "HomeCallout")
    HomeAbout = apps.get_model("home", "HomeAbout")

    em_uso = any(
        Model.objects.exists()
        for Model in (HomeSection, HomeCard, HomeCategoryCard, HomeCallout, HomeAbout)
    )
    if not em_uso:
        return

    produtos = list(HomeSection.objects.order_by("sort_order", "id"))
    ordem = []

    if HomeCategoryCard.objects.exists():
        categorias = HomeSection.objects.create(
            internal_name="Categorias em destaque", section_type="category_cards", is_active=True
        )
        HomeCategoryCard.objects.update(section=categorias)
        ordem.append(categorias)

    ordem.extend(produtos)

    como = HomeSection.objects.create(
        internal_name="Como trabalhamos", section_type="how_we_work", is_active=True
    )
    HomeCard.objects.update(section=como)
    ordem.append(como)

    chamada = HomeCallout.objects.order_by("id").first()
    if chamada is not None and not chamada.internal_name:
        chamada.internal_name = "Chamada final"
        chamada.save(update_fields=["internal_name"])
    ordem.append(
        HomeSection.objects.create(
            internal_name="Chamada final", section_type="callout", callout=chamada, is_active=True
        )
    )

    sobre = HomeAbout.objects.order_by("id").first()
    if sobre is not None:
        if not sobre.internal_name:
            sobre.internal_name = "Sobre a loja"
            sobre.save(update_fields=["internal_name"])
        ordem.append(
            HomeSection.objects.create(
                internal_name="Sobre a loja", section_type="about", about=sobre, is_active=True
            )
        )

    for posicao, secao in enumerate(ordem):
        secao.sort_order = posicao * 10
        secao.save(update_fields=["sort_order"])


def descompor(apps, schema_editor):
    """Solta o conteúdo das seções antes de apagá-las — nada em cascata."""
    HomeSection = apps.get_model("home", "HomeSection")
    apps.get_model("home", "HomeCard").objects.update(section=None)
    apps.get_model("home", "HomeCategoryCard").objects.update(section=None)
    HomeSection.objects.filter(section_type__in=BLOCOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_banner_carousel_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'ordering': ('id',), 'verbose_name': 'bloco Sobre a loja', 'verbose_name_plural': 'SOBRE A LOJA — quadro de imagem e texto'},
        ),
        migrations.AlterModelOptions(
            name='homecallout',
            options={'ordering': ('id',), 'verbose_name': 'chamada final da Home', 'verbose_name_plural': 'CHAMADA FINAL — faixa do fim da Home'},
        ),
        migrations.AddField(
            model_name='homeabout',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text='Para reconhecer o bloco na lista. Não aparece para o cliente.', max_length=120, verbose_name='nome interno'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text="Para reconhecer o texto na lista (ex.: 'Chamada — Natal'). Não aparece para o cliente.", max_length=120, verbose_name='nome interno'),
        ),
        migrations.AddField(
            model_name='homecard',
            name='section',
            field=models.ForeignKey(help_text="A seção 'Como trabalhamos' em que este card aparece.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.homesection', verbose_name='seção'),
        ),
        migrations.AddField(
            model_name='homecategorycard',
            name='section',
            field=models.ForeignKey(help_text="A seção 'Categorias em destaque' em que este bloco aparece.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_cards', to='home.homesection', verbose_name='seção'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='about',
            field=models.ForeignKey(blank=True, help_text="Usado só no tipo 'Sobre a loja'. Sem escolher, a seção não é desenhada.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='home.homeabout', verbose_name='sobre a loja (conteúdo)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='callout',
            field=models.ForeignKey(blank=True, help_text="Usada só no tipo 'Chamada final'. Sem escolher, a seção mostra o texto padrão.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='home.homecallout', verbose_name='chamada final (conteúdo)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcado, as seções que usam este bloco não são desenhadas.', verbose_name='exibir na Home'),
        ),
        migrations.AlterField(
            model_name='homecallout',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcado, as seções que usam este texto não são desenhadas.', verbose_name='exibir na Home'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('manual', 'Produtos escolhidos manualmente'), ('category', 'Produtos de uma categoria'), ('featured', 'Produtos em destaque'), ('newest', 'Novidades (produtos mais recentes)'), ('best_sellers', 'Mais vendidos (aguarda o módulo de pedidos)'), ('category_cards', 'Categorias em destaque (blocos coloridos)'), ('how_we_work', 'Como trabalhamos (cards com ícone)'), ('callout', 'Chamada final (faixa com botão e passos)'), ('about', 'Sobre a loja (quadro de imagem e texto)')], default='featured', max_length=20, verbose_name='tipo'),
        ),
        migrations.RunPython(compor, descompor),
    ]
