# Generated by Django 6.1 on 2026-09-06 21:47

"""A Home vira uma composição — a etapa de SCHEMA.

Os blocos que tinham posição fixa no template (categorias em destaque, como
trabalhamos, chamada final, sobre a loja) passam a ser seções de
`HomeSection`: esta migration cria os campos e as chaves estrangeiras que
isso pede (`section` em card e bloco, `callout`/`about` na seção, o nome
interno da chamada e do "Sobre a loja", os novos tipos de seção).

A migração dos DADOS — criar as seções que representam a página de hoje e
ligar o conteúdo existente a elas — fica na 0010_home_composition_data. As
duas eram uma só e falhavam no PostgreSQL: gravar linhas pelas FKs recém-
criadas (DEFERRABLE INITIALLY DEFERRED) na mesma transação do schema deixa
eventos de trigger pendentes, e o schema editor não consegue fechar a etapa
("cannot CREATE INDEX ... because it has pending trigger events").
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_banner_carousel_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeabout',
            options={'ordering': ('id',), 'verbose_name': 'bloco Sobre a loja', 'verbose_name_plural': 'SOBRE A LOJA — quadro de imagem e texto'},
        ),
        migrations.AlterModelOptions(
            name='homecallout',
            options={'ordering': ('id',), 'verbose_name': 'chamada final da Home', 'verbose_name_plural': 'CHAMADA FINAL — faixa do fim da Home'},
        ),
        migrations.AddField(
            model_name='homeabout',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text='Para reconhecer o bloco na lista. Não aparece para o cliente.', max_length=120, verbose_name='nome interno'),
        ),
        migrations.AddField(
            model_name='homecallout',
            name='internal_name',
            field=models.CharField(blank=True, default='', help_text="Para reconhecer o texto na lista (ex.: 'Chamada — Natal'). Não aparece para o cliente.", max_length=120, verbose_name='nome interno'),
        ),
        migrations.AddField(
            model_name='homecard',
            name='section',
            field=models.ForeignKey(help_text="A seção 'Como trabalhamos' em que este card aparece.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.homesection', verbose_name='seção'),
        ),
        migrations.AddField(
            model_name='homecategorycard',
            name='section',
            field=models.ForeignKey(help_text="A seção 'Categorias em destaque' em que este bloco aparece.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_cards', to='home.homesection', verbose_name='seção'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='about',
            field=models.ForeignKey(blank=True, help_text="Usado só no tipo 'Sobre a loja'. Sem escolher, a seção não é desenhada.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='home.homeabout', verbose_name='sobre a loja (conteúdo)'),
        ),
        migrations.AddField(
            model_name='homesection',
            name='callout',
            field=models.ForeignKey(blank=True, help_text="Usada só no tipo 'Chamada final'. Sem escolher, a seção mostra o texto padrão.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='home.homecallout', verbose_name='chamada final (conteúdo)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcado, as seções que usam este bloco não são desenhadas.', verbose_name='exibir na Home'),
        ),
        migrations.AlterField(
            model_name='homecallout',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarcado, as seções que usam este texto não são desenhadas.', verbose_name='exibir na Home'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(choices=[('manual', 'Produtos escolhidos manualmente'), ('category', 'Produtos de uma categoria'), ('featured', 'Produtos em destaque'), ('newest', 'Novidades (produtos mais recentes)'), ('best_sellers', 'Mais vendidos (aguarda o módulo de pedidos)'), ('category_cards', 'Categorias em destaque (blocos coloridos)'), ('how_we_work', 'Como trabalhamos (cards com ícone)'), ('callout', 'Chamada final (faixa com botão e passos)'), ('about', 'Sobre a loja (quadro de imagem e texto)')], default='featured', max_length=20, verbose_name='tipo'),
        ),
    ]
