# Generated by Django 6.1 on 2026-08-24 23:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_seed_delivery_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('code', models.SlugField(help_text='Identificador curto e estável: bpost, dpd, gls...', max_length=40, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('tracking_url_template', models.URLField(blank=True, help_text='Endereço de acompanhamento com {tracking} no lugar do código. Ex.: https://track.bpost.cloud/btr/web/#/search?itemCode={tracking}', max_length=300, verbose_name='URL de rastreio')),
            ],
            options={
                'verbose_name': 'transportadora',
                'verbose_name_plural': 'transportadoras',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('code', models.SlugField(help_text='Identificador curto: standard, express...', max_length=40, verbose_name='código')),
                ('description', models.CharField(blank=True, help_text='Uma linha, mostrada no checkout.', max_length=160, verbose_name='descrição')),
                ('min_days', models.PositiveIntegerField(default=2, help_text='Tempo de transporte, sem a produção.', verbose_name='prazo mínimo (dias úteis)')),
                ('max_days', models.PositiveIntegerField(default=3, verbose_name='prazo máximo (dias úteis)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingcarrier', verbose_name='transportadora')),
            ],
            options={
                'verbose_name': 'método de entrega',
                'verbose_name_plural': 'métodos de entrega',
                'ordering': ('sort_order', 'carrier__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('min_weight_grams', models.PositiveIntegerField(default=0, help_text='Inclusivo.', verbose_name='peso mínimo (g)')),
                ('max_weight_grams', models.PositiveIntegerField(blank=True, help_text='Exclusivo. Em branco = sem limite (última faixa).', null=True, verbose_name='peso máximo (g)')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='core.deliverycountry', verbose_name='país')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod', verbose_name='método')),
            ],
            options={
                'verbose_name': 'tarifa de entrega',
                'verbose_name_plural': 'tarifas de entrega',
                'ordering': ('country__sort_order', 'method__sort_order', 'min_weight_grams'),
            },
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.UniqueConstraint(fields=('carrier', 'code'), name='shipping_method_unique_code'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['country', 'min_weight_grams'], name='shipping_rate_lookup_idx'),
        ),
    ]
