# Generated by Django 6.1 on 2026-08-24 14:27

import apps.catalog.models
import apps.core.models
import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('website', models.URLField(blank=True, verbose_name='site')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='slug')),
                ('hex_code', models.CharField(blank=True, help_text='Ex.: #000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, por exemplo #FF0000.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')], verbose_name='código HEX')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'cor',
                'verbose_name_plural': 'cores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sku', models.CharField(help_text='Código interno único. Ex.: GATO-POMPOM-01', max_length=64, unique=True, verbose_name='SKU')),
                ('slug', models.SlugField(blank=True, help_text='Identificador para URL. Se deixado em branco, é gerado a partir do nome em português. URLs por idioma poderão ser adicionadas depois com um slug por tradução.', max_length=220, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('inactive', 'Inativo')], db_index=True, default='draft', max_length=16, verbose_name='status')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='largura')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='altura')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='profundidade')),
                ('dimension_unit', models.CharField(choices=[('mm', 'Milímetro (mm)'), ('cm', 'Centímetro (cm)'), ('m', 'Metro (m)'), ('in', 'Polegada (in)')], default='mm', max_length=4, verbose_name='unidade das dimensões')),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Sempre em gramas. A unidade é fixa para permitir cálculo de frete.', max_digits=10, null=True, verbose_name='peso (g)')),
                ('print_time', models.DurationField(blank=True, help_text='Formato HH:MM:SS. Ex.: 02:35:00 para 2 horas e 35 minutos.', null=True, verbose_name='tempo de impressão')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dólar americano ($)'), ('GBP', 'Libra esterlina (£)'), ('BRL', 'Real brasileiro (R$)')], default='EUR', max_length=3, verbose_name='moeda')),
                ('filament_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='custo de filamento')),
                ('energy_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='custo de energia')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado automaticamente a partir dos componentes de custo.', max_digits=10, verbose_name='custo total')),
                ('pricing_mode', models.CharField(choices=[('price', 'Informar preço de venda (margem calculada)'), ('margin', 'Informar margem de lucro (preço calculado)')], default='price', max_length=8, verbose_name='definir preço por')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço de venda')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Margem sobre o preço de venda: (preço - custo) / preço × 100.', max_digits=5, null=True, verbose_name='margem de lucro (%)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('allow_backorder', models.BooleanField(default=False, help_text='Permite vender mesmo com estoque zerado.', verbose_name='permitir venda sem estoque')),
                ('made_to_order', models.BooleanField(default=False, verbose_name='produto sob encomenda')),
                ('production_lead_time_days', models.PositiveIntegerField(blank=True, help_text='Obrigatório para produtos sob encomenda.', null=True, verbose_name='prazo médio de produção (dias)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='produto em destaque')),
                ('featured_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primeiro na home.', verbose_name='ordem no destaque')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='marca')),
                ('category', models.ForeignKey(blank=True, help_text='Obrigatória para ativar o produto. Subcategoria é apenas uma categoria que possui pai.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='categoria')),
                ('colors', models.ManyToManyField(blank=True, help_text='Cores do produto base. Migrará para a variante no futuro.', related_name='products', to='catalog.color', verbose_name='cores')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('materials', models.ManyToManyField(blank=True, related_name='products', to='catalog.material', verbose_name='materiais')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('-created_at',),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('GIF', 'GIF')], default='IMAGE', max_length=8, verbose_name='tipo')),
                ('file', models.FileField(upload_to=apps.catalog.models.product_media_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avif', 'gif', 'jpeg', 'jpg', 'm4v', 'mov', 'mp4', 'png', 'webm', 'webp']), apps.catalog.models.validate_media_file_size], verbose_name='arquivo')),
                ('alt_text', models.CharField(blank=True, help_text='Descrição da mídia para acessibilidade e SEO.', max_length=200, verbose_name='texto alternativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_primary', models.BooleanField(default=False, help_text='Apenas uma mídia por produto pode ser a principal.', verbose_name='imagem principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'mídia do produto',
                'verbose_name_plural': 'mídias do produto',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('short_description', models.CharField(blank=True, help_text='Usada em cards, resultados de busca e listagens.', max_length=300, verbose_name='descrição curta')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('extra_information', models.TextField(blank=True, help_text='Cuidados, instruções de uso, avisos.', verbose_name='informações adicionais')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'tradução do produto',
                'verbose_name_plural': 'traduções do produto',
                'ordering': ('language',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-created_at'], name='product_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'featured_order'], name='product_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='product_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('filament_cost__gte', 0)), name='product_filament_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('energy_cost__gte', 0)), name='product_energy_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='product_total_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='product_sale_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('profit_margin__isnull', True), models.Q(('profit_margin__gte', Decimal('-999.99')), ('profit_margin__lte', Decimal('100.00'))), _connector='OR'), name='product_profit_margin_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__isnull', True), ('weight_grams__gte', 0), _connector='OR'), name='product_weight_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('width__isnull', True), ('width__gte', 0), _connector='OR'), name='product_width_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('height__isnull', True), ('height__gte', 0), _connector='OR'), name='product_height_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('depth__isnull', True), ('depth__gte', 0), _connector='OR'), name='product_depth_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('print_time__isnull', True), ('print_time__gte', datetime.timedelta(0)), _connector='OR'), name='product_print_time_not_negative'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'sort_order'], name='product_media_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='product_media_single_primary'),
        ),
        migrations.AddConstraint(
            model_name='producttranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='product_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='producttranslation',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_translation_name_not_empty'),
        ),
    ]
