# Generated by Django 6.1 on 2026-08-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='personalization_text_limit',
            field=models.PositiveIntegerField(default=200, help_text='Usado quando a personalização aceita texto.', verbose_name='limite de caracteres do texto'),
        ),
        migrations.AddField(
            model_name='product',
            name='personalization_type',
            field=models.CharField(choices=[('none', 'Nenhuma'), ('photo', 'Foto (obrigatória)'), ('text', 'Texto (obrigatório)'), ('photo_or_text', 'Foto ou texto (o cliente escolhe)')], default='none', help_text='Define se o cliente deverá fornecer uma foto, um texto ou escolher entre os dois antes de adicionar o produto ao carrinho.', max_length=16, verbose_name='tipo de personalização'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sku', models.CharField(help_text='Código próprio desta variante. Ex.: CANECA-PRETO-300', max_length=64, unique=True, verbose_name='SKU')),
                ('size', models.CharField(blank=True, help_text='Como o cliente vê. Ex.: "15 cm", "300 ml".', max_length=60, verbose_name='tamanho')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o preço do produto.', max_digits=10, null=True, verbose_name='preço de venda')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade em estoque')),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o peso do produto.', max_digits=10, null=True, verbose_name='peso (g)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='largura')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='altura')),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='profundidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='cor')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.material', verbose_name='material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'variante',
                'verbose_name_plural': 'variantes',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['product', 'is_active'], name='variant_product_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='variant_sale_price_not_negative'), models.CheckConstraint(condition=models.Q(('weight_grams__isnull', True), ('weight_grams__gte', 0), _connector='OR'), name='variant_weight_not_negative')],
            },
        ),
    ]
