# Generated by Django 6.1 on 2026-08-26 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_seed_color_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Como o material aparece no Admin. O nome que o cliente lê vem das traduções.', max_length=80, unique=True, verbose_name='nome interno'),
        ),
        migrations.CreateModel(
            name='MaterialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.material', verbose_name='material')),
            ],
            options={
                'verbose_name': 'tradução do material',
                'verbose_name_plural': 'traduções do material',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='material_translation_unique_language'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='material_translation_name_not_empty')],
            },
        ),
    ]
