# Generated by Django 6.1 on 2026-08-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_material_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Opcional. Vinculada a uma variante, esta foto passa a ser a imagem principal quando o cliente escolher essa opção. Em branco, é foto geral do produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='catalog.productvariant', verbose_name='variante'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['variant'], name='product_media_variant_idx'),
        ),
    ]
