# Generated by Django 6.1 on 2026-09-07 21:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_media_variant_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_mode',
            field=models.CharField(choices=[('none', 'Não se aplica'), ('single', 'Uma cor'), ('multi', 'Multicolorido'), ('custom', 'Cores à escolha do cliente'), ('variant', 'Opção comercial (a cor é escolhida na variante)')], default='none', help_text='Como a cor funciona neste produto. «Uma cor» e «Multicolorido» descrevem a peça (lista abaixo, não cria variantes); «Cores à escolha» é informativo; «Opção comercial» mantém a cor como eixo de cada variante.', max_length=8, verbose_name='modo de cores'),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_uses', to='catalog.color', verbose_name='cor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'cor do produto',
                'verbose_name_plural': 'cores do produto',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['product', 'sort_order'], name='product_color_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'color'), name='product_color_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional, de 0 a 100. Em branco, só o material é mostrado.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='percentual')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='catalog.material', verbose_name='material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_composition', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'material da composição',
                'verbose_name_plural': 'composição de materiais',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['product', 'sort_order'], name='product_material_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'material'), name='product_material_composition_unique'), models.CheckConstraint(condition=models.Q(('percentage__isnull', True), models.Q(('percentage__gte', 0), ('percentage__lte', 100)), _connector='OR'), name='product_material_percentage_range')],
            },
        ),
    ]
