# Generated by Django 6.1 on 2026-09-08 11:49

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_derive_color_mode_and_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, verbose_name='nome interno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'opção do produto',
                'verbose_name_plural': 'opções do produto',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOptionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.productoption', verbose_name='opção')),
            ],
            options={
                'verbose_name': 'tradução da opção',
                'verbose_name_plural': 'traduções da opção',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, verbose_name='nome interno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.productoption', verbose_name='opção')),
            ],
            options={
                'verbose_name': 'valor da opção',
                'verbose_name_plural': 'valores da opção',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductOptionValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.productoptionvalue', verbose_name='valor')),
            ],
            options={
                'verbose_name': 'tradução do valor',
                'verbose_name_plural': 'traduções do valor',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariantOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variant_links', to='catalog.productoption', verbose_name='opção')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variant_links', to='catalog.productoptionvalue', verbose_name='valor')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'opção da variante',
                'verbose_name_plural': 'opções da variante',
                'ordering': ('option__sort_order', 'option_id'),
            },
        ),
        migrations.AddIndex(
            model_name='productoption',
            index=models.Index(fields=['product', 'sort_order'], name='product_option_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='product_option_unique'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_option_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productoptiontranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='product_option_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='productoptiontranslation',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_option_translation_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='productoptionvalue',
            index=models.Index(fields=['option', 'sort_order'], name='product_option_value_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'name'), name='product_option_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_option_value_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvaluetranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='product_option_value_translation_unique_language'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvaluetranslation',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='product_option_value_translation_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='productvariantoptionvalue',
            index=models.Index(fields=['variant', 'value'], name='variant_option_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantoptionvalue',
            constraint=models.UniqueConstraint(fields=('variant', 'option'), name='variant_option_unique'),
        ),
    ]
