# Generated by Django 6.1 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
    ]
