# Generated by Django 6.1 on 2026-09-09 23:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_material_translation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='price_delta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Quanto esta cor soma ao preço da variante quando o cliente a escolhe. Só vale em «Cores à escolha do cliente»; 0 não altera o preço.', max_digits=10, verbose_name='adicional (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_mode',
            field=models.CharField(choices=[('none', 'Não se aplica'), ('single', 'Uma cor'), ('multi', 'Multicolorido'), ('custom', 'Cores à escolha do cliente'), ('variant', 'Opção comercial (a cor é escolhida na variante)')], default='none', help_text='Como a cor funciona neste produto. «Uma cor» e «Multicolorido» descrevem a peça (lista abaixo, não cria variantes); «Cores à escolha do cliente» oferece as cores da paleta na compra, com adicional opcional, sem criar variantes; «Opção comercial» mantém a cor como eixo de cada variante.', max_length=8, verbose_name='modo de cores'),
        ),
    ]
