# Generated by Django 6.1 on 2026-09-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productcolor_price_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_composite',
            field=models.BooleanField(default=False, editable=False, help_text='Marcada sozinha quando a cor tem componentes.', verbose_name='cor composta'),
        ),
        migrations.CreateModel(
            name='ColorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='catalog.color', verbose_name='cor composta')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composed_in', to='catalog.color', verbose_name='componente')),
            ],
            options={
                'verbose_name': 'componente da cor',
                'verbose_name_plural': 'componentes da cor',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='color',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='composites', through='catalog.ColorComponent', through_fields=('color', 'component'), to='catalog.color', verbose_name='componentes'),
        ),
        migrations.AddIndex(
            model_name='colorcomponent',
            index=models.Index(fields=['color', 'sort_order'], name='color_component_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='colorcomponent',
            constraint=models.UniqueConstraint(fields=('color', 'component'), name='color_component_unique'),
        ),
        migrations.AddConstraint(
            model_name='colorcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('color', models.F('component')), _negated=True), name='color_component_not_self'),
        ),
    ]
