# Generated by Django 6.1 on 2026-09-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_color_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='color_choice_label',
            field=models.CharField(blank=True, help_text='Só em «Cores à escolha do cliente»: o nome da parte que o cliente pinta, no lugar de «Cor». Ex.: «Cor do pompom». Em branco, a loja escreve «Cor» no idioma do cliente.', max_length=60, verbose_name='rótulo da cor à escolha'),
        ),
    ]
