# Generated by Django 6.1 on 2026-08-27 20:07

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(max_length=120, verbose_name='nome interno')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'coluna do rodapé',
                'verbose_name_plural': 'RODAPÉ — colunas de links',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='telefone de contato')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado, o rodapé volta aos textos padrão do template.', verbose_name='usar este rodapé')),
            ],
            options={
                'verbose_name': 'rodapé',
                'verbose_name_plural': 'RODAPÉ — textos e contato',
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('url', models.CharField(blank=True, help_text='Caminho interno (/algo) ou endereço http/https. Em branco, o item aparece como texto — útil para página em construção.', max_length=500, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='storefront.footercolumn', verbose_name='coluna')),
            ],
            options={
                'verbose_name': 'link do rodapé',
                'verbose_name_plural': 'links do rodapé',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(help_text='Identificação administrativa. Não aparece para o cliente.', max_length=120, verbose_name='nome interno')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Menor valor aparece primeiro.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'item da faixa do topo',
                'verbose_name_plural': 'FAIXA DO TOPO — promessas curtas',
                'ordering': ('sort_order', 'id'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='topbar_active_order_idx')],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FooterColumnTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(max_length=80, verbose_name='título')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.footercolumn', verbose_name='coluna')),
            ],
            options={
                'verbose_name': 'tradução da coluna',
                'verbose_name_plural': 'traduções da coluna',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='footer_column_translation_unique_language')],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('label', models.CharField(max_length=120, verbose_name='texto do link')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.footerlink', verbose_name='link')),
            ],
            options={
                'verbose_name': 'tradução do link',
                'verbose_name_plural': 'traduções do link',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='footer_link_translation_unique_language')],
            },
        ),
        migrations.CreateModel(
            name='FooterSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('about_text', models.TextField(blank=True, help_text='O parágrafo ao lado do logo.', verbose_name='texto institucional')),
                ('categories_title', models.CharField(blank=True, help_text='A lista em si continua vindo das categorias cadastradas.', max_length=80, verbose_name='título da coluna de categorias')),
                ('contact_title', models.CharField(blank=True, max_length=80, verbose_name='título do bloco de contato')),
                ('copyright_text', models.CharField(blank=True, help_text='Deixe em branco para usar o texto padrão com o ano corrente.', max_length=200, verbose_name='texto de copyright')),
                ('badge_text', models.CharField(blank=True, help_text='O texto ao lado do escudo (hoje: "Compra segura").', max_length=80, verbose_name='selo do rodapé')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.footersettings', verbose_name='rodapé')),
            ],
            options={
                'verbose_name': 'tradução do rodapé',
                'verbose_name_plural': 'traduções do rodapé',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='footer_translation_unique_language')],
            },
        ),
        migrations.CreateModel(
            name='TopBarItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('text', models.CharField(max_length=120, verbose_name='texto')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.topbaritem', verbose_name='item')),
            ],
            options={
                'verbose_name': 'tradução do item',
                'verbose_name_plural': 'traduções do item',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='topbar_translation_unique_language')],
            },
        ),
    ]
