# Generated by Django 6.1 on 2026-08-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbaritem',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Sem ícone'), ('cube', 'Cubo (produção)'), ('palette', 'Paleta (cores e materiais)'), ('truck', 'Caminhão (envio)'), ('sparkles', 'Brilho (personalização)'), ('shield', 'Escudo (segurança)'), ('clock', 'Relógio (prazo)'), ('package', 'Caixa (embalagem)')], default='', help_text='Usado só na lista do hero. A faixa do topo é sempre só texto.', max_length=20, verbose_name='ícone'),
        ),
    ]
