# Generated by Django 6.1 on 2026-08-27 21:41

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_topbaritem_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('slug', models.CharField(choices=[('envios-e-prazos', 'Envios e prazos'), ('trocas-e-devolucoes', 'Trocas e devoluções'), ('contato', 'Contato'), ('revenda', 'Seja um revendedor')], help_text='Qual das páginas da loja este conteúdo preenche.', max_length=40, unique=True, verbose_name='página')),
                ('is_active', models.BooleanField(default=True, help_text='Despublicada, a página some do rodapé e mostra só o formulário, quando houver.', verbose_name='publicada')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='mostrar no rodapé')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem no rodapé')),
            ],
            options={
                'verbose_name': 'página institucional',
                'verbose_name_plural': 'PÁGINAS — envios, trocas, contato e revenda',
                'ordering': ('sort_order', 'slug'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='assunto')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('language', models.CharField(blank=True, help_text='Em que idioma a pessoa escreveu.', max_length=5, verbose_name='idioma')),
                ('is_handled', models.BooleanField(default=False, verbose_name='já respondida')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'CONTATO — mensagens recebidas',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='contact_handled_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('company', models.CharField(max_length=160, verbose_name='empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=40, verbose_name='telefone')),
                ('country', models.CharField(max_length=80, verbose_name='país')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('business_type', models.CharField(max_length=120, verbose_name='tipo de negócio')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='idioma')),
                ('is_handled', models.BooleanField(default=False, verbose_name='já respondido')),
            ],
            options={
                'verbose_name': 'pedido de revenda',
                'verbose_name_plural': 'REVENDA — pedidos recebidos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='reseller_handled_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='título')),
                ('intro', models.TextField(blank=True, help_text='Um parágrafo curto abaixo do título. Nas páginas com formulário, aparece acima dele.', verbose_name='introdução')),
                ('body', models.TextField(blank=True, help_text='O conteúdo da página. Uma linha em branco separa parágrafos; uma linha começando com # vira subtítulo.', verbose_name='texto')),
                ('meta_description', models.CharField(blank=True, help_text='Em branco, usa a introdução.', max_length=300, verbose_name='descrição para buscadores')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.institutionalpage', verbose_name='página')),
            ],
            options={
                'verbose_name': 'tradução da página',
                'verbose_name_plural': 'traduções da página',
                'ordering': ('language',),
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='institutional_page_unique_language')],
            },
        ),
    ]
