# Generated by Django 6.1 on 2026-08-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_institutionalpage_contactmessage_resellerapplication_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resellerapplication',
            name='reseller_handled_idx',
        ),
        migrations.DeleteModel(
            name='ResellerApplication',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Aponte para uma página da loja em vez de digitar o endereço: o link acompanha o idioma do visitante.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_links', to='storefront.institutionalpage', verbose_name='página da loja'),
        ),
    ]
