# Generated by Django 6.1 on 2026-09-04 11:20

import apps.core.colors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_seed_institutional_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='accent_color',
            field=models.CharField(default='#b48cf0', help_text='O "Print" do nome, no rodapé. Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor de destaque da logo'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='heading_color',
            field=models.CharField(default='white', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor dos títulos das colunas'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='surface_color',
            field=models.CharField(default='navy', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='fundo'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='text_color',
            field=models.CharField(default='ink-on-deep', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto'),
        ),
        migrations.AddField(
            model_name='topbaritem',
            name='color',
            field=models.CharField(default='yellow', help_text='A faixa alterna cores de propósito — amarelo, menta e coral no desenho da marca. Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do texto'),
        ),
        migrations.AddField(
            model_name='topbaritem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Opcional. Com um endereço, o item vira link.', max_length=500, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='topbaritem',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Sem ícone'), ('cube', 'Cubo (produção)'), ('palette', 'Paleta (cores e materiais)'), ('truck', 'Caminhão (envio)'), ('sparkles', 'Brilho (personalização)'), ('shield', 'Escudo (segurança)'), ('clock', 'Relógio (prazo)'), ('package', 'Caixa (embalagem)')], default='', help_text='Opcional. Aparece antes do texto, na faixa e na lista do hero.', max_length=20, verbose_name='ícone'),
        ),
    ]
