# Generated by Django 6.1 on 2026-09-05 15:15

import apps.core.colors
import apps.core.models
import apps.core.uploads
import apps.storefront.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_home_visual_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('internal_name', models.CharField(help_text='Só para o Admin: "Lançamento outubro", "Manutenção do servidor".', max_length=120, verbose_name='nome interno')),
                ('kind', models.CharField(choices=[('maintenance', 'Manutenção'), ('launch', 'Lançamento')], default='maintenance', max_length=20, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=False, help_text='⚠️ ATIVAR ESTA PÁGINA BLOQUEARÁ O SITE PÚBLICO: todo visitante passa a ver só esta página, em qualquer endereço. Só uma página fica ativa por vez — ativar esta desativa a outra. O Admin continua acessível, e quem está logado como equipe segue vendo a loja normal para testar.', verbose_name='ativa')),
                ('logo', models.FileField(blank=True, help_text='Opcional. Sem arquivo, o header mostra a marca desenhada (sigla + nome) abaixo.', upload_to=apps.storefront.models.special_page_upload_to, validators=[django.core.validators.FileExtensionValidator(('svg', 'png', 'webp', 'avif', 'jpg', 'jpeg', 'gif')), apps.core.uploads.validate_brand_image], verbose_name='logo (arquivo)')),
                ('logo_mark', models.CharField(default='JD', help_text='As letras dentro do quadradinho roxo do header.', max_length=4, verbose_name='sigla da marca')),
                ('logo_text', models.CharField(default='JD Print', max_length=40, verbose_name='nome da marca')),
                ('logo_url', models.CharField(blank=True, help_text='Para onde a logo leva. Vazio = a própria página.', max_length=500, verbose_name='link da marca')),
                ('status_color', models.CharField(default='yellow', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor do ponto de status')),
                ('status_pulse', models.BooleanField(default=True, help_text='O ponto do status pisca devagar (o desenho da manutenção). Desligue para um ponto fixo.', verbose_name='ponto pulsando')),
                ('primary_enabled', models.BooleanField(default=True, verbose_name='botão principal ligado')),
                ('primary_url', models.CharField(blank=True, help_text='Endereço completo (https://…), mailto:… ou um caminho do site.', max_length=500, verbose_name='link do botão principal')),
                ('secondary_enabled', models.BooleanField(default=True, verbose_name='botão secundário ligado')),
                ('secondary_url', models.CharField(blank=True, max_length=500, verbose_name='link do botão secundário')),
                ('show_progress', models.BooleanField(default=True, help_text='Dentro do cartão da impressora.', verbose_name='mostrar porcentagem e barra')),
                ('progress_percent', models.PositiveSmallIntegerField(default=68, help_text='De 0 a 100. É só uma indicação para o visitante — nada é medido.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='porcentagem')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='data do lançamento')),
                ('launch_time', models.TimeField(blank=True, null=True, verbose_name='hora do lançamento')),
                ('launch_timezone', models.CharField(default='Europe/Brussels', help_text='A data e a hora acima valem neste fuso. O navegador do visitante converte para o dele.', max_length=64, verbose_name='fuso horário')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='mostrar contagem regressiva')),
                ('show_form', models.BooleanField(default=True, help_text='O e-mail fica em CONFIGURAÇÕES DA LOJA › Inscritos do lançamento.', verbose_name='mostrar formulário de aviso')),
                ('sticker_1_tone', models.CharField(choices=[('yellow', 'Amarelo'), ('mint', 'Menta'), ('coral', 'Coral'), ('white', 'Branco com contorno'), ('purple', 'Roxo')], default='yellow', max_length=10, verbose_name='tom do selo 1')),
                ('sticker_2_tone', models.CharField(choices=[('yellow', 'Amarelo'), ('mint', 'Menta'), ('coral', 'Coral'), ('white', 'Branco com contorno'), ('purple', 'Roxo')], default='mint', max_length=10, verbose_name='tom do selo 2')),
                ('sticker_3_tone', models.CharField(choices=[('yellow', 'Amarelo'), ('mint', 'Menta'), ('coral', 'Coral'), ('white', 'Branco com contorno'), ('purple', 'Roxo')], default='white', max_length=10, verbose_name='tom do selo 3')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_url', models.URLField(blank=True, help_text='Ex.: https://wa.me/32470000000', verbose_name='WhatsApp')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('surface_color', models.CharField(default='cream', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='fundo da página')),
                ('brand_color', models.CharField(default='purple', help_text='O poster do lançamento; na manutenção, o botão, a placa e a palavra destacada. Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor principal')),
                ('brand_text_color', models.CharField(default='white', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='texto sobre a cor principal')),
                ('accent_color', models.CharField(default='yellow', help_text='A tag, a palavra marcada no lançamento, a barra e o botão do formulário. Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='cor de destaque')),
                ('accent_text_color', models.CharField(default='navy', help_text='Uma cor da marca (creme, navy, purple, yellow, mint, coral, lavender…) ou um hexadecimal como <code>#4A1A8C</code>.', max_length=20, validators=[apps.core.colors.validate_color], verbose_name='texto sobre o destaque')),
            ],
            options={
                'verbose_name': 'página de manutenção ou lançamento',
                'verbose_name_plural': 'MANUTENÇÃO E LANÇAMENTO — páginas especiais',
                'ordering': ('-is_active', '-updated_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='storefront_one_active_special_page')],
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialPageBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tone', models.CharField(choices=[('yellow', 'Amarelo'), ('mint', 'Menta'), ('coral', 'Coral'), ('white', 'Branco com contorno'), ('purple', 'Roxo')], default='mint', max_length=10, verbose_name='cor do marcador')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='storefront.specialpage', verbose_name='página')),
            ],
            options={
                'verbose_name': 'benefício da página especial',
                'verbose_name_plural': 'MANUTENÇÃO E LANÇAMENTO — benefícios',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LaunchSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='idioma')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='storefront.specialpage', verbose_name='página de origem')),
            ],
            options={
                'verbose_name': 'inscrito do lançamento',
                'verbose_name_plural': 'MANUTENÇÃO E LANÇAMENTO — inscritos',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='storefront_subscriber_email_ci')],
            },
        ),
        migrations.CreateModel(
            name='SpecialPageBenefitTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('text', models.CharField(max_length=80, verbose_name='texto')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.specialpagebenefit', verbose_name='benefício')),
            ],
            options={
                'verbose_name': 'tradução do benefício',
                'verbose_name_plural': 'traduções do benefício',
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='uq_specialpagebenefit_translation')],
            },
        ),
        migrations.CreateModel(
            name='SpecialPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('status_text', models.CharField(blank=True, help_text='A pílula ao lado da logo: "Manutenção programada", "Lançamento em breve".', max_length=60, verbose_name='status (header)')),
                ('eyebrow', models.CharField(blank=True, help_text='A tarja amarela acima do título.', max_length=60, verbose_name='tag')),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('title_highlight', models.CharField(blank=True, help_text='Uma palavra ou trecho do título, copiado exatamente. Sai roxo (manutenção) ou na pílula amarela (lançamento).', max_length=80, verbose_name='trecho destacado do título')),
                ('description', models.TextField(blank=True, help_text='Trechos entre ** saem em negrito: "Lançamos no dia **1 de outubro** às **10:00**".', verbose_name='texto')),
                ('primary_label', models.CharField(blank=True, max_length=60, verbose_name='texto do botão principal')),
                ('secondary_label', models.CharField(blank=True, max_length=60, verbose_name='texto do botão secundário')),
                ('progress_label', models.CharField(blank=True, help_text='Manutenção: sob a barra. Ex.: "Imprimindo a nova versão…".', max_length=80, verbose_name='legenda do progresso')),
                ('sticker_1', models.CharField(blank=True, max_length=40, verbose_name='selo 1')),
                ('sticker_2', models.CharField(blank=True, max_length=40, verbose_name='selo 2')),
                ('sticker_3', models.CharField(blank=True, max_length=40, verbose_name='selo 3')),
                ('footer_text', models.CharField(blank=True, help_text='Ex.: "© 2026 JD Print · Feito na Bélgica".', max_length=120, verbose_name='texto do rodapé')),
                ('countdown_done_text', models.CharField(blank=True, help_text='Lançamento: o que aparece quando a data chega. Ex.: "Já lançamos! Bem-vindo."', max_length=120, verbose_name='texto ao zerar a contagem')),
                ('form_placeholder', models.CharField(blank=True, max_length=60, verbose_name='campo de e-mail (placeholder)')),
                ('form_button_label', models.CharField(blank=True, max_length=60, verbose_name='botão do formulário')),
                ('form_note', models.CharField(blank=True, help_text='Ex.: "Sem spam. Só o aviso de lançamento e o cupom."', max_length=160, verbose_name='nota sob o formulário')),
                ('form_success_text', models.CharField(blank=True, help_text='Depois de deixar o e-mail. Ex.: "Pronto! Avisamos você no lançamento 🎉"', max_length=160, verbose_name='texto de sucesso')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.specialpage', verbose_name='página')),
            ],
            options={
                'verbose_name': 'tradução da página',
                'verbose_name_plural': 'traduções da página',
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='uq_specialpage_translation')],
            },
        ),
    ]
