# Generated by Django 6.1 on 2026-09-11 07:29

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_special_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPageNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Desligado, o aviso não aparece — os textos continuam guardados.', verbose_name='ativo')),
                ('page', models.OneToOneField(help_text='Cada página de lançamento tem no máximo um aviso.', limit_choices_to={'kind': 'launch'}, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='storefront.specialpage', verbose_name='página de lançamento')),
            ],
            options={
                'verbose_name': 'aviso do lançamento',
                'verbose_name_plural': 'MANUTENÇÃO E LANÇAMENTO — aviso do lançamento',
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialPageNoticeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('text', models.CharField(help_text='Ex.: «Frete grátis no lançamento! Aproveite.» Texto livre: não muda nenhuma regra de frete.', max_length=160, verbose_name='texto')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.specialpagenotice', verbose_name='aviso')),
            ],
            options={
                'verbose_name': 'tradução do aviso',
                'verbose_name_plural': 'traduções do aviso',
                'constraints': [models.UniqueConstraint(fields=('master', 'language'), name='uq_specialpagenotice_translation')],
            },
        ),
    ]
