# Generated by Django 6.1 on 2026-09-11 08:17

import apps.core.models
import apps.storefront.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_special_page_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_active', models.BooleanField(default=True, help_text='Desligado, o aviso some da loja. Nada é apagado.', verbose_name='ativo')),
                ('dismissible', models.BooleanField(default=True, help_text='Mostra um X. Quem fecha não vê mais este aviso ao navegar — até ele ser alterado: um texto ou link novo volta a aparecer para todos.', verbose_name='permitir fechar')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Menor aparece primeiro. Na mesma posição, as faixas se empilham nesta ordem; no canto aparece um card por vez — fechado, dá lugar ao seguinte.', verbose_name='ordem')),
                ('pages', models.JSONField(default=apps.storefront.models.default_notice_pages, help_text='As áreas da loja em que o aviso aparece.', validators=[apps.storefront.models.validate_notice_pages], verbose_name='onde exibir')),
                ('position', models.CharField(choices=[('below_banner', 'Abaixo do banner — faixa de destaque no fluxo da página'), ('top', 'Topo da página — faixa fina acima do cabeçalho'), ('after_content', 'Após o conteúdo principal — discreto, antes do rodapé'), ('corner', 'Canto inferior direito — card flutuante, como uma mensagem')], default='below_banner', help_text='Abaixo do banner é a faixa de destaque da Home; nas páginas sem banner, ela abre o conteúdo, logo abaixo do cabeçalho.', max_length=20, verbose_name='posição')),
                ('link_url', models.CharField(blank=True, help_text='Opcional. Um caminho da loja (/modelos/), um endereço completo (https://…), mailto: ou tel:. Sem link, o aviso é só texto.', max_length=500, verbose_name='link')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'AVISOS — faixas e cards da loja',
                'ordering': ('sort_order', 'id'),
            },
            bases=(apps.core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StoreNoticeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('fr', 'Francês'), ('nl', 'Holandês'), ('en', 'Inglês'), ('de', 'Alemão'), ('es', 'Espanhol'), ('it', 'Italiano'), ('tr', 'Turco'), ('ar', 'Árabe')], db_index=True, default='pt', max_length=5, verbose_name='idioma')),
                ('title', models.CharField(blank=True, help_text='Opcional. Sai em negrito, antes da mensagem.', max_length=80, verbose_name='título')),
                ('message', models.CharField(help_text='O texto do aviso. Curto: uma ou duas frases.', max_length=240, verbose_name='mensagem')),
                ('link_label', models.CharField(blank=True, help_text='Opcional. Só aparece se o aviso tiver link; vazio, o link diz «Saiba mais».', max_length=40, verbose_name='texto do link')),
            ],
            options={
                'verbose_name': 'tradução do aviso',
                'verbose_name_plural': 'traduções do aviso',
            },
        ),
        migrations.RemoveField(
            model_name='specialpagenotice',
            name='page',
        ),
        migrations.RemoveConstraint(
            model_name='specialpagenoticetranslation',
            name='uq_specialpagenotice_translation',
        ),
        migrations.AddField(
            model_name='storenoticetranslation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='storefront.storenotice', verbose_name='aviso'),
        ),
        migrations.RemoveField(
            model_name='specialpagenoticetranslation',
            name='master',
        ),
        migrations.AddConstraint(
            model_name='storenoticetranslation',
            constraint=models.UniqueConstraint(fields=('master', 'language'), name='uq_storenotice_translation'),
        ),
        migrations.DeleteModel(
            name='SpecialPageNotice',
        ),
        migrations.DeleteModel(
            name='SpecialPageNoticeTranslation',
        ),
    ]
